export const TODO_POST_REQUEST = "TODO_POST_REQUEST";
export const TODO_POST_SUCCESS = "TODO_POST_SUCCESS";
export const TODO_POST_FAIL = "TODO_POST_FAIL";
export const TODO_POST_REST = "TODO_POST_REST";

export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAIL = "GET_TODO_FAIL";

export const TODO_EDIT_REQUEST = "TODO_EDIT_REQUEST";
export const TODO_EDIT_SUCCESS = "TODO_EDIT_SUCCESS";
export const TODO_EDIT_FAIL = "TODO_EDIT_FAIL";

export const GET_SINGLETODO_REQUEST = "GET_SINGLETODO_REQUEST";
export const GET_SINGLE_TODO_SUCCESS = "GET_SINGLE_TODO_SUCCESS";
export const GET_SINGLE_TODO_FAIL = "GET_SINGLE_TODO_FAIL";

export const REST_SINGLETODO = "REST_SINGLETODO";

export const TODO_DELETE_REQUEST = "TODO_DELETE_REQUEST";
export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS";
export const TODO_DELETE_FAIL = "TODO_DELETE_FAIL";
